### ISSUE TITLE
aux.h and aux.cpp can't be checked out on windows

### ISSUE THREAD

**Issue by uwewoessner** [vrsys/lamure#17]
Iamure can't be checked out on windows because aux is a reserverd filename on windows.
Could you please rename it to e.g. prov_aux.h/cpp

error: unable to create file provenance/include/lamure/prov/aux.h: No such file or directory
error: unable to create file provenance/src/aux.cpp: No such file or directory

**Comment by xyzrgbcarl** [comment]
Resolved
